name: cargo-deny

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cargo-deny:
    uses: chrisliebaer/.github/.github/workflows/cargo-deny.yml@c7b49aac6c730cdd2b84a7be4391eeaa43a18ef6 # master
