name: actionlint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  actionlint:
    uses: chrisliebaer/workflows/.github/workflows/actionlint.yml@c7b49aac6c730cdd2b84a7be4391eeaa43a18ef6 # master
