[advisories]
yanked = "deny"


ignore = [
	# no fix available
	"RUSTSEC-2023-0071",
	# this one we should actually fix
	"RUSTSEC-2024-0363",
]

[licenses]


[[licenses.exceptions]]
name = "ring"
allow = ["MIT", "ISC", "OpenSSL"]

[[licenses.exceptions]]
name = "webpki-roots"
allow = ["MPL-2.0"]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
