[advisories]
yanked = "deny"

ignore = [
	# no fix available
	"RUSTSEC-2023-0071",
]

[licenses]

exceptions = [
		# ring is using multiple intermangled licenses
		{ allow = ["ISC", "OpenSSL"], name = "ring" },
		{ allow = ["MPL-2.0"], name = "webpki-roots" }
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
