# actual workflow, not just a reusable action
name: actionlint-call

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  actionlint:
    uses: ./.github/workflows/actionlint.yml
