name: actionlint

on:
  workflow_call:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: docker://rhysd/actionlint:latest
        with:
          args: -color
