name: actionlint

on:
  workflow_call:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: docker://rhysd/actionlint:latest
        with:
          args: -color
