name: cargo-deny

on:
  workflow_call:
    inputs:
      path:
        description: "Path to Cargo.toml directory"
        type: string
        default: "."
      rust-version:
        description: "Rust version to use"
        type: string
        default: "stable"

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # cargo-deny is a bit clunky. we manually merge local overrides into the toml
      # also docker image forces non-root user, so we need to run as root
      # which is why we can't use githubs `use: docker://...` syntax
      # toml merge will overwrite existing arrays, so very careful with the patch file
      - run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace --user root ghcr.io/mesosphere/toml-merge:v0.2.0 --verbose 9 --patch-file deny.patch.toml --in-place deny.toml

      # print our masterpiece for debugging
      - run: cat deny.toml

      - uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2
        with:
          rust-version: ${{ inputs.rust-version }}
          manifest-path: ${{ inputs.path }}/Cargo.toml
          arguments: --workspace
          command: check ${{ matrix.checks }}
