name: cargo-deny

on:
  workflow_call:
    inputs:
      path:
        description: "Path to Cargo.toml directory"
        type: string
        default: "."
      rust-version:
        description: "Rust version to use"
        type: string
        default: "stable"

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: ${{ inputs.rust-version }}
          arguments: --workspace --manifest-path=${{ inputs.path }}/Cargo.toml
          command: check ${{ matrix.checks }}
