name: clippy

on:
  workflow_call:
    inputs:
      path:
        description: "Path to Cargo.toml directory"
        type: string
        default: "."
      rust-version:
        description: "Rust version to use"
        type: string
        default: "stable"


jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - run: rustup install --profile minimal ${{ inputs.rust-version }}
      - run: rustup override set ${{ inputs.rust-version }}
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
      - run: >
          cargo clippy --all-targets --all-features --workspace --no-deps --tests --
          -D clippy::cargo
          -D warnings
          -A clippy::multiple_crate_versions
        working-directory: ${{ inputs.path }}
