name: clippy

on:
  workflow_call:
    inputs:
      path:
        description: "Path to Cargo.toml directory"
        type: string
        default: "."
      rust-version:
        description: "Rust version to use"
        type: string
        default: "stable"


jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: rustup install --profile minimal ${{ inputs.rust-version }}
      - run: rustup override set ${{ inputs.rust-version }}
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
      - run: >
          cargo clippy --all-targets --all-features --workspace --no-deps --tests --
          -D clippy::cargo
          -D warnings
          -A clippy::multiple_crate_versions
        working-directory: ${{ inputs.path }}
